server:
  port: 8081
spring:
  cloud:
    stream:
      defaultBinder: kafka
      default:
        contentType: application/json
      function:
        definition: clinicalCompletedConsumer
      bindings:
        clinicalCompletedConsumer-in-0:
          destination: his.clinical.visit-completed
          group: billingClinicalCompletedGroup
      kafka:
        bindings:
          clinicalCompletedConsumer-in-0:
            consumer:
              startOffset: earliest
        binder:
          brokers: ${KAFKA_BROKERS:192.168.1.60}
          defaultBrokerPort: ${KAFKA_BROKER_PORT:9092}
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.67:1521:XE
    username: HOSPITAL
    password: 1111

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

toss:
    secret-key: ${TOSS_SECRET_KEY}
    base-url: https://api.tosspayments.com

patient:
  api:
    base-url: ${PATIENT_API_BASE_URL:http://192.168.1.60:8181}
